#!/bin/bash

# Script to download and prepare 3D character models with blend shapes for ChroNexa
# This script helps download models suitable for lip sync animation

echo "================================"
echo "ChroNexa Model Downloader"
echo "================================"
echo ""
echo "This script will help you download 3D character models with blend shapes."
echo ""
echo "RECOMMENDED FREE SOURCES:"
echo ""
echo "1. MIXAMO (https://www.mixamo.com)"
echo "   - Adobe's character library"
echo "   - Many rigged characters with facial animations"
echo "   - Free with Adobe account"
echo "   - Download as: FBX with blend shapes"
echo "   - Then convert to GLB using Blender/gltf-pipeline"
echo ""
echo "2. SKETCHFAB (https://sketchfab.com)"
echo "   - Search: 'character' + 'download' filter"
echo "   - Look for 'Rigged' models"
echo "   - Check if model has facial animations (morph targets)"
echo "   - Many free models available"
echo ""
echo "3. POLY HAVEN (https://polyhaven.com/models)"
echo "   - Free 3D models"
echo "   - Some characters with blend shapes"
echo "   - CC0 license"
echo ""
echo "================================"
echo "SETUP INSTRUCTIONS:"
echo "================================"
echo ""
echo "Step 1: Download a model with blend shapes"
echo "  - Recommended formats: FBX, GLTF/GLB"
echo "  - Models MUST have facial animations/blend shapes"
echo ""
echo "Step 2: Convert to GLB (if needed)"
echo "  - Use Blender: File > Export > glTF 2.0 (.glb/.gltf)"
echo "  - Or use gltf-pipeline:"
echo "    npm install -g gltf-pipeline"
echo "    gltf-pipeline -i model.fbx -o model.glb"
echo ""
echo "Step 3: Place in public folder"
echo "  cp model.glb frontend/public/"
echo ""
echo "Step 4: Update avatar service to use new model"
echo "  Edit: frontend/src/services/avatar.ts"
echo "  Change: const modelUrl = '/model.glb'"
echo ""
echo "================================"
echo "RECOMMENDED MODELS TO DOWNLOAD:"
echo "================================"
echo ""
echo "OPTION 1: Sci-Fi Girl (Sketchfab)"
echo "  URL: https://sketchfab.com/3d-models/scifi-girl-v01-96340701c2ed4d37851c7d9109eee9c0"
echo "  Size: Good quality, has facial animations"
echo "  Download: GLB format recommended"
echo ""
echo "OPTION 2: Female Character (Mixamo)"
echo "  URL: https://www.mixamo.com"
echo "  Search: 'Female' or 'Woman'"
echo "  Select model with facial expressions"
echo "  Download as: FBX + Blend Shapes"
echo ""
echo "OPTION 3: Doctor Character (Sketchfab)"
echo "  URL: Search 'doctor character' on Sketchfab"
echo "  Look for rigged models with animations"
echo ""
echo "================================"
echo "QUICK START - DOWNLOAD AND TEST"
echo "================================"
echo ""
echo "# Example: Download a model from URL"
echo "curl -L 'MODEL_URL' -o frontend/public/new_avatar.glb"
echo ""
echo "# Update avatar.ts to use new model"
echo "sed -i \"\" \"s|'/pablo_doctor.glb'|'/new_avatar.glb'|g\" frontend/src/services/avatar.ts"
echo ""
echo "# Refresh browser to test"
echo ""
echo "================================"
echo ""
echo "Need help? Check LIP_SYNC_GUIDE.md for detailed information."
